name: Deploy StyleDivaa

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            if [ ! -d "/home/styledivaauser/public_html/.git" ]; then
                rm -rf /home/styledivaauser/public_html  # Ensure the folder is empty
                git clone --depth=1 "https://github.com/vatsalrishabh/styledivaa.git" /home/styledivaauser/public_html
            else
                cd /home/styledivaauser/public_html || exit 1
                git fetch --all
                git reset --hard origin/main
            fi
            cd /home/styledivaauser/public_html || exit 1
            chown -R styledivaauser:styledivaauser /home/styledivaauser/public_html  # Fix ownership
            npm install --force  # Force install in case of partial downloads
            npm run build
            pm2 restart styledivaa || pm2 start npm --name "styledivaa" -- run start
            pm2 save
          EOF
